### ISSUE TITLE
add support for `nimpretty` to format on save

### ISSUE THREAD

**Issue by pouriyajamshidi** [nim-lang/vscode-nim#108]
Hi,

Thanks for working on Nim's tooling. The experience has definitely improved.

I was wondering if you have any plans adding support for running `nimpretty` to format the code on save?

Not sure if it already exists but at least I could not find it.

Thanks in advance

**Comment by jmgomez** [comment]
We just released a new version that adds support for `formatting` via `nph` see https://forum.nim-lang.org/t/12525

**Comment by pouriyajamshidi** [comment]
The issue was about nimpretty. isn't nimpretty the official formatter for Nim?

**Comment by jmgomez** [comment]
It's the default formatter for the `nimlangserver` as people seemed to like it more. That said, feel free to submit a PR that opt-in it.

**Comment by metaleap** [comment]
@jmgomez question: should a PR for this preferably be done for `vscode-nim` or for `nimlangserver` from the `vscode-nim` project's point of view?

Ie. does this extension run the LSP format command on nimlangserver, or does it manually run nph on the VSC API formatting request without involving the LSP. Because it seems like you do the latter when I hear:

> It's the default formatter for the nimlangserver as people seemed to like it more.

But I wonder why when `nimlangserver` seems to "default no `nph` if installed" anyway.

I'll make sure I can `nimpretty`-on-save at my end, ideally via PR to either `vscode-nim` or `nimlangserver` (hence my above question) because I won't be limited to 88 columns in 2025 by "opinionated" software — I'm just as opinionated as it  :grin:  — so thanks in advance for clarifying.

**Comment by jmgomez** [comment]
> should a PR for this preferably be done for vscode-nim or for nimlangserver from the vscode-nim project's point of view?

In the langserver please. Should be an opt-in `nimlangserver.useNimPretty` as we do with others options. Since `nimpretty` is ship with `nim` make sure it uses the right nim. There is a helper `getNimPath` in the lsp code for this. Take a look at how `nim check` is implemented

**Comment by arnetheduck** [comment]
> In the langserver please. Should be an opt-in `nimlangserver.useNimPretty` as we do with others options. Since `nimpretty` is ship with `nim` make sure it uses the right nim. There is a helper `getNimPath` in the lsp code for this. Take a look at how `nim check` is implemented

an option might be to have the option specify a "formatter binary", which the user can set to any binary they like - that would of course rely on the binaries exposing the same CLI option

**Comment by metaleap** [comment]
> an option might be to have the option specify a "formatter binary", which the user can set to any binary they like - that would of course rely on the binaries exposing the same CLI option

How about letting them specify not a command but the full command line, with the setting, if not set, defaulting to however `nimlangserver` currently runs `nph` — asking because `nph` and `nimpretty` already have mostly-differing sets of command-line args.

**Comment by jmgomez** [comment]
It will be easier to maintain from both the user point of view and the developer too (i.e. now the user need to change nimpretty each project in order to use the right version, when thats already solved by the lsp)  to just do the `nimlangserver.useNimPretty: true` thing. 
Or if you want it to be extended with others in the future : `nimlangserver.formatter: "nimpretty"` defaulting to `nph`
